services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - appnet

  mongodb:
    image: mongo:8.0.14
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - appnet

  api_common_questions:
    build: 
      context: ..
      dockerfile: ./deployment/api_common_questions/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - appnet

  ingestion:
    build:
      context: ../ingestion
      dockerfile: ../ingestion/Dockerfile
    container_name: ingestion
    depends_on:
      mongodb:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    volumes:
      - ../ingestion:/app
    working_dir: /app/src
    command: python load_data.py
    networks:
      - appnet

volumes:
  esdata:
  mongodata:

networks:
  appnet:
    driver: bridge