version: '3.8'

services:
  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - elasticsearch

  airflow:
    build: ./airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - mongodb

volumes:
  esdata:
  mongodata: