services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=prontotodoacabara
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - appnet

  kibana:
    image: bitnami/kibana:8.10.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=prontotodoacabara
    depends_on:
      - elasticsearch
    networks:
      - appnet

  mongodb:
    image: mongo:8.0.14
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - appnet

  api_common_questions:
    build: 
      context: ..
      dockerfile: ./deployment/api_common_questions/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - appnet

volumes:
  esdata:
  mongodata:

networks:
  appnet:
    driver: bridge
