# location_mapping.py
# Mapeo estático de IDs de localización (0–300) a barrios y calles de Madrid

location_mapping = {
    # 🏙️ Barrios y zonas (0–149)
    0: "Centro",
    1: "Sol",
    2: "Cortes",
    3: "Embajadores",
    4: "Lavapiés",
    5: "Justicia",
    6: "Universidad",
    7: "Malasaña",
    8: "Chueca",
    9: "Palacio",
    10: "La Latina",
    11: "Argüelles",
    12: "Moncloa",
    13: "Chamberí",
    14: "Gaztambide",
    15: "Trafalgar",
    16: "Almagro",
    17: "Ríos Rosas",
    18: "Vallehermoso",
    19: "Salamanca",
    20: "Recoletos",
    21: "Goya",
    22: "Lista",
    23: "Castellana",
    24: "Guindalera",
    25: "Fuente del Berro",
    26: "Retiro",
    27: "Pacífico",
    28: "Adelfas",
    29: "Estrella",
    30: "Ibiza",
    31: "Niño Jesús",
    32: "Arganzuela",
    33: "Imperial",
    34: "Acacias",
    35: "Chopera",
    36: "Legazpi",
    37: "Delicias",
    38: "Palos de Moguer",
    39: "Usera",
    40: "Orcasitas",
    41: "Almendrales",
    42: "Moscardó",
    43: "Pradolongo",
    44: "Orcasur",
    45: "Carabanchel",
    46: "Vista Alegre",
    47: "Puerta Bonita",
    48: "Opañel",
    49: "Comillas",
    50: "San Isidro",
    51: "Abrantes",
    52: "Villaverde",
    53: "Los Rosales",
    54: "Butarque",
    55: "San Cristóbal",
    56: "Los Ángeles",
    57: "Puente de Vallecas",
    58: "Numancia",
    59: "San Diego",
    60: "Palomeras Bajas",
    61: "Palomeras Sureste",
    62: "Entrevías",
    63: "Portazgo",
    64: "Moratalaz",
    65: "Pavones",
    66: "Marroquina",
    67: "Horcajo",
    68: "Media Legua",
    69: "Fontarrón",
    70: "Ciudad Lineal",
    71: "Ventas",
    72: "Quintana",
    73: "San Pascual",
    74: "San Juan Bautista",
    75: "Colina",
    76: "Concepción",
    77: "Pueblo Nuevo",
    78: "Costillares",
    79: "Hortaleza",
    80: "Pinar del Rey",
    81: "Canillas",
    82: "Canillejas",
    83: "Valdefuentes",
    84: "Barajas",
    85: "Alameda de Osuna",
    86: "Timón",
    87: "Corralejos",
    88: "Rejas",
    89: "Salvador",
    90: "Simancas",
    91: "San Blas",
    92: "Amposta",
    93: "Arcos",
    94: "Rosas",
    95: "Ensanche de Vallecas",
    96: "Santa Eugenia",
    97: "Villa de Vallecas",
    98: "Casco Histórico de Vallecas",
    99: "Vicálvaro",
    100: "Casco Histórico de Vicálvaro",
    101: "Valdebernardo",
    102: "Valderrivas",
    103: "El Cañaveral",
    104: "San Fermín",
    105: "El Espinillo",
    106: "Los Cármenes",
    107: "Lucero",
    108: "Aluche",
    109: "Campamento",
    110: "Las Águilas",
    111: "Cuatro Vientos",
    112: "Casa de Campo",
    113: "Aravaca",
    114: "El Plantío",
    115: "Valdemarín",
    116: "El Pardo",
    117: "Mirasierra",
    118: "Peñagrande",
    119: "El Pilar",
    120: "La Paz",
    121: "Valverde",
    122: "Montecarmelo",
    123: "Las Tablas",
    124: "Sanchinarro",
    125: "Valdefuentes Norte",
    126: "San Blas Norte",
    127: "Las Rosas",
    128: "Canillas Norte",
    129: "Arturo Soria",
    130: "Prosperidad",
    131: "Ciudad Jardín",
    132: "El Viso",
    133: "Castilla",
    134: "Nueva España",
    135: "Hispanoamérica",
    136: "Bernabéu",
    137: "Cuatro Caminos",
    138: "Raimundo Fernández Villaverde",
    139: "Cuatro Torres",
    140: "Tetuán",
    141: "Bellas Vistas",
    142: "Valdeacederas",
    143: "Berruguete",
    144: "Castillejos",
    145: "Cuatro Caminos Sur",
    146: "Azca",
    147: "Orense",
    148: "Cuzco",
    149: "Plaza de Castilla",

    # 🚦 Calles y avenidas (150–300)
    150: "Gran Vía",
    151: "Calle de Alcalá",
    152: "Paseo del Prado",
    153: "Calle de Serrano",
    154: "Calle de Velázquez",
    155: "Calle de Goya",
    156: "Paseo de la Castellana",
    157: "Calle de Fuencarral",
    158: "Calle de Hortaleza",
    159: "Calle de Toledo",
    160: "Calle Mayor",
    161: "Calle de Preciados",
    162: "Calle de Atocha",
    163: "Calle de Embajadores",
    164: "Calle de Bravo Murillo",
    165: "Calle de Princesa",
    166: "Calle de San Bernardo",
    167: "Calle de Alberto Aguilera",
    168: "Calle de Génova",
    169: "Calle de O’Donnell",
    170: "Calle de Ibiza",
    171: "Calle del Doctor Esquerdo",
    172: "Calle de Narváez",
    173: "Calle de Claudio Coello",
    174: "Calle de Jorge Juan",
    175: "Calle de Don Ramón de la Cruz",
    176: "Calle de Hermosilla",
    177: "Calle de Lagasca",
    178: "Calle de Ortega y Gasset",
    179: "Calle del Príncipe de Vergara",
    180: "Calle de López de Hoyos",
    181: "Calle de Cartagena",
    182: "Calle de Francisco Silvela",
    183: "Calle de Diego de León",
    184: "Calle de Raimundo Fernández Villaverde",
    185: "Calle de Santa Engracia",
    186: "Calle de José Abascal",
    187: "Calle de Ríos Rosas",
    188: "Calle de Ponzano",
    189: "Calle de Bravo Murillo Norte",
    190: "Calle de Sor Ángela de la Cruz",
    191: "Avenida de América",
    192: "Avenida de los Toreros",
    193: "Avenida de Menéndez Pelayo",
    194: "Avenida de la Albufera",
    195: "Avenida de Pablo Neruda",
    196: "Avenida de Entrevías",
    197: "Avenida de la Paz (M-30)",
    198: "Avenida del Mediterráneo",
    199: "Avenida de Valladolid",
    200: "Avenida de Reina Victoria",
    201: "Avenida de Filipinas",
    202: "Avenida de Portugal",
    203: "Avenida de Oporto",
    204: "Avenida de Andalucía",
    205: "Avenida de Córdoba",
    206: "Avenida de los Poblados",
    207: "Avenida de Arcentales",
    208: "Avenida de Logroño",
    209: "Avenida de la Ilustración",
    210: "Avenida del Cardenal Herrera Oria",
    211: "Calle de Sinesio Delgado",
    212: "Calle de Ginzo de Limia",
    213: "Calle de Fermín Caballero",
    214: "Calle de Islas Filipinas",
    215: "Calle de Guzmán el Bueno",
    216: "Calle de Isaac Peral",
    217: "Calle de Altamirano",
    218: "Calle de Rosales",
    219: "Calle de Bailén",
    220: "Calle del Ferrocarril",
    221: "Calle del Comercio",
    222: "Calle de Antonio López",
    223: "Calle de Marcelo Usera",
    224: "Calle de Dolores Barranco",
    225: "Calle de Tomás Bretón",
    226: "Calle de Canarias",
    227: "Calle de Valencia",
    228: "Calle del Doctor Fourquet",
    229: "Calle del Amparo",
    230: "Calle de la Fe",
    231: "Calle del Espíritu Santo",
    232: "Calle de San Mateo",
    233: "Calle de Pelayo",
    234: "Calle del Barquillo",
    235: "Calle del Conde Duque",
    236: "Calle de San Vicente Ferrer",
    237: "Calle de la Palma",
    238: "Calle de Espíritu Santo Norte",
    239: "Calle del Pez",
    240: "Calle de San Bernardo Norte",
    241: "Calle de Princesa Norte",
    242: "Calle de Ferraz",
    243: "Calle del Marqués de Urquijo",
    244: "Calle de Quintana",
    245: "Calle de Altamirano Norte",
    246: "Calle de Tutor",
    247: "Calle de la Princesa Oeste",
    248: "Calle de Ventura Rodríguez",
    249: "Calle de Amaniel",
    250: "Calle de Conde Duque Norte",
    251: "Calle de Leganitos",
    252: "Calle de San Vicente",
    253: "Calle de Cuesta de San Vicente",
    254: "Calle de Bailén Sur",
    255: "Calle de Ferraz Oeste",
    256: "Calle de Pintor Rosales",
    257: "Calle de Quintana Oeste",
    258: "Calle de Tutor Norte",
    259: "Calle de Romero Robledo",
    260: "Calle de Moret",
    261: "Calle de Vallehermoso Norte",
    262: "Calle de Bravo Murillo Oeste",
    263: "Calle de Sor Ángela de la Cruz Norte",
    264: "Calle de Marqués de Viana",
    265: "Calle de Sinesio Delgado Norte",
    266: "Calle de Ofelia Nieto",
    267: "Calle de Francos Rodríguez",
    268: "Calle de Jerónima Llorente",
    269: "Calle de Almansa",
    270: "Calle de Escosura",
    271: "Calle de Cea Bermúdez",
    272: "Calle de Arapiles",
    273: "Calle de Galileo",
    274: "Calle de Blasco de Garay",
    275: "Calle de Fernando el Católico",
    276: "Calle de Guzmán el Bueno Norte",
    277: "Calle de Vallehermoso Sur",
    278: "Calle de Esquilache",
    279: "Calle de Magallanes",
    280: "Calle de Rodríguez San Pedro",
    281: "Calle de Fuencarral Norte",
    282: "Calle de San Bernardo Sur",
    283: "Calle del Espíritu Santo Sur",
    284: "Calle de Palma Norte",
    285: "Calle de Velarde",
    286: "Calle de Manuela Malasaña",
    287: "Calle de Ruiz",
    288: "Calle de Palafox",
    289: "Calle de Carranza",
    290: "Calle de Sagasta",
    291: "Calle de Génova Oeste",
    292: "Calle de Almagro Norte",
    293: "Calle de Miguel Ángel",
    294: "Calle de Eduardo Dato",
    295: "Calle de Fortuny",
    296: "Calle de Zurbano",
    297: "Calle de Caracas",
    298: "Calle de Monte Esquinza",
    299: "Calle de Bárbara de Braganza",
    300: "Calle de Marqués de la Ensenada"
}
